### ISSUE TITLE
numpy.testing.Tester not available in numpy>1.24

### ISSUE THREAD

**Issue by m-albert** [vladanl/Pyto#5]
Hi, thanks for this library! I'm currently trying it out as a dependency of [`surface_morphometrics`](https://github.com/GrotjahnLab/surface_morphometrics) and just wanted to report here that I ran into this error after pip installing Pyto:

> ImportError: cannot import name 'Tester' from 'numpy.testing'

I fixed this by downgrading numpy to `numpy==1.24`, since this is the last version in which `numpy.testing.Tester` is available.

I'd expect others to run into this error too, which I guess could be prevented by requiring numpy<=1.24 in `Pyto` :)

Thanks!

**Comment by vladanl** [comment]
Thank you for spotting this. I just removed all numpy.testing.tester imports

**Comment by m-albert** [comment]
Thank you for fixing @vladanl :)
